services:
  business-service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  business-service-notification-worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3001
    command: ["node", "dist/internal/content/workers/notification.worker.js"]
    restart: unless-stopped
